#pragma once

#include "util/Profiler.h"

#include <glad/glad.h>

#include "Audio.h"
#include "CPL.h"
#include "Engine.h"
#include "Screenshot.h"
#include "Shader.h"
#include "Text.h"
#include "shape2D/Circle.h"
#include "shape2D/GlobalLight.h"
#include "shape2D/Line.h"
#include "shape2D/ParticleSystem.h"
#include "shape2D/PointLight.h"
#include "shape2D/Rectangle.h"
#include "shape2D/ScreenQuad.h"
#include "shape2D/Texture2D.h"
#include "shape2D/Tilemap.h"
#include "shape2D/Triangle.h"
#include "shape3D/Cube.h"
#include "shape3D/CubeMap.h"
#include "shape3D/CubeTex.h"
#include "shape3D/DirectionalLight.h"
#include "shape3D/Frustum.h"
#include "shape3D/PlaneTex.h"
#include "shape3D/PointLight3D.h"
#include "shape3D/ShadowMap.h"
#include "shape3D/Sphere.h"
#include "timer/TimerManager.h"
#include "util/Logging.h"
#include "util/OpenGLDebug.h"
#include "util/ScopedTimer.h"
#include <GLFW/glfw3.h>
